config/routes.rb
Hnclone::Application.routes.draw do

  root to: "links#index"
  
  resources :links do 
    resources :comments
    resources :votes
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :title, :url
  
  belongs_to :user
  has_many :comments
  has_many :votes
  
  before_save :format_url
  
  validates_uniqueness_of :url
  validates_presence_of :title
  
  private
    def format_url
      self.url = 'http://' << self.url unless self.url.include?('http://') or self.url.include?('https://')
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation
  has_secure_password
  
  before_save :create_remember_token
  
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  has_many :links
  has_many :comments
  has_many :votes
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :value
  
  belongs_to :user
  belongs_to :link
  
  validates_presence_of :value, :user, :link
  validates_uniqueness_of :link_id, :scope => [:user_id]
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  
  private
    def find_resource
      class_name = params[:controller].singularize
      klass = class_name.camelize.constantize
      self.instance_variable_set "@" + class_name, klass.find(params[:id])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @link = Link.find(params[:link_id])

    @comment = @link.comments.build(params[:comment])
    @comment.user = current_user

    if @comment.save
      flash[:success] = "Comment saved!"
      redirect_to link_path(@link)
    else
      flash[:error] = "Your comment was not saved"
      redirect_to link_path(@link)
    end
  end
  
  def show
    @comment = Comment.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :find_resource, :only => [:show, :edit, :update, :destroy]
  
  # GET /links
  # GET /links.json
  def index
    @links = Link.scoped.page(params[:page]).per(30)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @comments = @link.comments
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    if current_user
    
      @link = Link.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @link }
      end
    else
      flash[:error] = 'You have to be logged in to submit a comment'
      redirect_to signin_path
    end
  end

  # GET /links/1/edit
  def edit
    if @link.user.id != current_user.id
      redirect_to link_path(@link)
      flash[:error] = "Only the author can edit this link"
    end
  end

  # POST /links
  # POST /links.json
  def create
    
    @link = current_user.links.create(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by_name(params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_path
    else
      flash[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to HNclone!"
      redirect_to root_path
    else
      render "new"
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController


  # POST /votes
  # POST /votes.json
  def create
    link = Link.find(params[:link_id])
    if link.user_id != current_user.id
      @vote = link.votes.build
      @vote.value = params[:value]
      @vote.user = current_user

      if @vote.save
        flash[:success] = "Thanks for the vote!"
      else
        flash[:error] = "Sorry, you cannot vote on the same link twice!"
      end
    else
      flash[:error] = "You cannot upvote your own link!"
    end

    redirect_to root_path
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "HNclone"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/comments/edit.html.erb
<h1>Editing comment</h1>


<%= render 'form' %>

app/views/comments/show.html.erb
<h1>Add Comment</h1>

<p><%= @comment.text %></p>
<p>posted by: <%= link_to @comment.user.name, user_path(@comment.user) %></p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    HNclone ©2012
  </small>
  <nav>
    <ul>
      <li><a href="http://natashatherobot.com/" target="_blank">NatashaTheRobot</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "HNclone", root_path, id: "logo" %>
      <nav>
		<ul class="nav pull-left">
			<li><%= link_to "submit", new_link_path %></li>
		</ul>
        <ul class="nav pull-right">
          <% if signed_in? %>
			<li><%= link_to current_user.name, current_user %></li>
			<li>
              <%= link_to "logout", signout_path, method: "delete" %>
			</li>
          <% else %>
            <li><%= link_to "login", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %> 
  </head>
  <body>
     <%= render 'layouts/header' %>
	   <div class="container">
		 <% flash.each do |key, value| %>
	        <div class="alert alert-<%= key %>"><%= value %></div>
	     <% end %>
	     <%= yield %>
	     <%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	   </div>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>


<%= render 'form' %>
	

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<%= paginate @links %>
<h1>Listing links</h1>


<% @links.each do |link| %>
  <ol>
    <li><%= link_to "upvote", link_votes_path(link, :value => 'up'), :method => :post %>
		<%= link_to link.title, link.url, :target => "_blank" %>
		<%= link_to "comments", link_path(link) %>
		<%= link_to "edit", edit_link_path(link) if link.user == current_user %>
	</li>	
  </ol>
<% end %>


<br />

app/views/links/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<%= link_to "upvote", link_votes_path(@link, :value => 'up'), :method => :post %>	
<%= link_to @link.title, @link.url, :target => "_blank"%>
</p>

<%= form_for([@link, @link.comments.build]) do |f| %>
  <div class="field">
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<ul>
	<% @comments.each do |comment| %>
		<li><%= comment.text %>
			<%= link_to "reply", link_comment_path(@link)%>
		</li>
	<% end %>	
</ul>	


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
	  <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
	
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
	  <p>Already a user? <%= link_to "Sign in!", signin_path %></p>	
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<ul>
  <li>user: <%= @user.name %></li>
  <li>created: <%= @user.created_at %></li>
	
</ul>